### PR TITLE
bump Guice dependency version from 4.1.0 to 4.2.0

### PR DESCRIPTION
**Pull request by vorburger**
see commit message for details

@mathieucarbou are you still maintaining this repo and willing to merge and would cut a release with this?

### CODE REVIEW

**Comment by vorburger** [comment]
@mathieucarbou lemme know if the EOL WS changes are an issue for you ([diff without WS here](https://github.com/mycila/guice/pull/15/files?utf8=✓&diff=split&w=1))

**Comment by vorburger** [comment]
@mathieucarbou the new TravisCI build failure is infra issue on Travis, not this change (fixed orig prob).

**Comment by vorburger** [comment]
@skitt I disagree with this view. In a "normal flat classpath Java" (non-OSGi) world, given that this project (mycila) uses Guice, which needs Guava, the right thing to do IMHO is to only have a dependency on Guice and let that decide the Guava version it wants, and then use that here. That is UNLESS this project needs a more recent version of Guava IFF that is still compatible with the chosen version of Guice - which it does not. Forcing a specific version of Guava serves no particular point IMHO. Else what are Maven transitive dependencies good for?

@mathieucarbou as the maintainer of this project, what's your view on this - want the explicit Guava dependency back in this PR, just bumped to a higher version?

**Comment by skitt** [comment]
@vorburger the sole purpose of transitive dependencies is to allow you to not care (too much) about your dependencies’ dependencies. Thus project A can depend on project B, without caring that project B depends on project C. Without transitive dependencies, project A would have to discover that project B depends on project C, and declare a dependency on project C itself. Transitive dependencies are *not* a means for project A to obtain project C via project B; if project A itself depends on project C, it also needs to depend on it explicitly.

**Comment by vorburger** [comment]
@mathieucarbou as the maintainer of this project, what's your view on this?

@skitt I understand what you are saying, but disagree with the view that this is better in Maven in this case.

**Comment by mathieucarbou** [comment]
sorry guys, I will close. this project has not been updated since years and I have no time now to keep maintaining it.

**Pull request closed without merging**
