### PR TITLE
add pom type for groovy

### PR DESCRIPTION
**Pull request by Fyro-Ing**
need pom type to retrieve groovy

### CODE REVIEW

**Comment by Fyro-Ing** [comment]
@mathieucarbou 

i would like to finalize & release a first version with guice 5.0.0. is there possibilities to give me temporary permissions to to this ?


https://github.com/mycila/pom/pull/4

**Review by mathieucarbou — APPROVED** [review]

**Comment by mathieucarbou** [comment]
> @mathieucarbou
> 
> i would like to finalize & release a first version with guice 5.0.0. is there possibilities to give me temporary permissions to to this ?
> 
> [mycila/pom#4](https://github.com/mycila/pom/pull/4)

I cannot give you the permissions because the sonatype UI does not allow me to give someone else the permission to push... I will have to do the releases.

**Comment by mathieucarbou** [comment]
I will remove this commit - dependency of type pom are wrong in this case.

**Comment by mathieucarbou** [comment]
> I will remove this commit - dependency of type pom are wrong in this case.

oh crap! I understand now why you had to do that! They have changed the way groovy-all is deployed. ok!

**Comment by mathieucarbou** [comment]
@Fyro-Ing : released ! Should be in Maven central soon ;-)

**Comment by Fyro-Ing** [comment]
thank you so much !

**Pull request merged**
